name: PrisonBridge
main: dev.kyro.wiji.prisonbridge.PrisonBridge
authors:
  - Kyro
  - wiji
version: 1.0.0
depend:
  - Prison
  - RevEnchants
  - PlaceholderAPI
commands:
  prisonbridge:
    aliases:
      - pb
  blocks:
  prestige:
  rankup:
  test: